### ISSUE TITLE
"Malformed decrypted payload, probably used the wrong key"

### ISSUE THREAD

**Issue by Gorkido** [mkst/zte-config-utility#27]
`python3 examples/decode.py --serial XXXXXXXXXXXXXX resources/config.bin resources/config.xml` outputs "Malformed decrypted payload, probably used the wrong key!" even though router's serial is right..

![image](https://user-images.githubusercontent.com/81165187/143016004-9db3a5ba-d6c3-4635-9f96-04ff061eb228.png)

**Comment by ufukcaneski** [comment]
I'm having the same problem, can anyone help?

**Comment by 811Alex** [comment]
This message means that the tool couldn't decode it, either due to the inputs used being wrong, or the model not being supported.
You've provided no info whatsoever, so Idk what you expect. I get hiding the serial, but why the model?

Anyway, if you think this is a type 4, maybe try again with the latest version. If it doesn't work, more info is definitely needed here (maybe the output of examples/info.py).

**Comment by mkst** [comment]
Closing as not enough information.
