### ISSUE TITLE
 H298A V9 Support

### ISSUE THREAD

**Issue by krmakmn** [mkst/zte-config-utility#35]
Hello. I have a ZTE H298A V9 Router. But your config utility doesn't support it. I am sending my router information.

MAC: 54:46:17:d6:b7:3f
SERIAL: ZT544617D6B73F
MODEL: ZTE H298A V9
CONFİG FİLE: https://drive.google.com/file/d/1-cZsy_Vx_EObA-PzEye4bBgB8UCkNffl/view?usp=sharing

Thanks for help.

**Comment by krmakmn** [comment]
@811Alex please help me.

**Comment by 811Alex** [comment]
I've lost most interest in projects like this, a major reason being that people that found me through here have been rather disrespectful to me, on average. To **anyone** coming across this, looking for help, from me, with their router: do not tag me, do **not** DM me. If you're looking for reverse engineering, I'm not interested atm. If the key/methodology is already discovered, I _might_ be interested in adding support to this tool, but that's it.

If you want to ask for help with a non-reverse-engineered model here, go ahead, maybe someone will take the time, but please leave _me_ alone, I'd generally rather allocate my time elsewhere.

**Comment by krmakmn** [comment]
@811Alex Ok. Then remove your name from the list of contributors. That way we don't care about you. Not everyone is tagging you for your enjoyment. We're asking if you can help here. Now you can go wherever you want.

**Comment by 811Alex** [comment]
I'm a contributor, not a collaborator. I do not have direct access to this repo, I have contributed to it. The only way to remove a contributor would be to rewrite the repo's history which would be incredibly dumb to do. Besides, the fact that some people don't have manners, does not mean I shouldn't be credited for my contributions. That is not a problem on my end.

You made the issue, you don't need to tag random people. We can see issues the same way you can.

**Comment by mkst** [comment]
Firstly, I am hugely grateful to everyone that helps out with this project, be that with direct code contributions, or that help people decoding their config files offline or other positive action. 

This is an open source project, therefore no-one is being paid for their time and as such no-one is under any obligation to help. 

This means that there should be no expectation from any users of this project for support - especially in the form of supporting new devices.

I am hugely disappointed that people have been directly messaging project contributors in a disrespectful manner. The tone of the messages from @krmakmn in particular is completely unacceptable and I will endeavour to do a better job of moderating the Issues section and reporting / deleting any messages that I deem offensive.

To all contributors - thank you again. 

To all users - be mindful that this project only exists because people decide to spend their free time on it; be polite and gracious. It's as simple as that.

**Comment by 811Alex** [comment]
I guess that's why the moment the problem was solved for **you** specifically, you closed the issue about a router many people have (issue not being solved for them) and didn't disclose your solution, on a project that's only backed by volunteers.

I will agree though, arrogance is terrible.

**Comment by nerossa** [comment]
> Hello. I have a ZTE H298A V9 Router. But your config utility doesn't support it. I am sending my router information.
> 
> MAC: 54:46:17:d6:b7:3f SERIAL: ZT544617D6B73F MODEL: ZTE H298A V9 CONFİG FİLE: https://drive.google.com/file/d/1-cZsy_Vx_EObA-PzEye4bBgB8UCkNffl/view?usp=sharing
> 
> Thanks for help.

How did you root your ZTE H298A V9
